
grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 3

model_selection:
  module_0: 
    class: KNeighborsClassifer
    module: sklearn.neighbors
    params:
      algorithm: kd_tree
      weights: uniform
      n_neighbors: 5
    search_param_grid:
      algorithm:
        - auto
        - ball_tree
        - kd_tree
        - brute
      weights:
        - uniform
        - distance
      n_neighbors:
        - 3
        - 5
        - 9

  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      max_depth: 100
      max_features: sqrt
      n_estimators: 3
    search_param_grid:
      max_depth:
      -10
      -15
      -20
      max_features:
      - auto
      - sqrt
      - log2
      n_estimators:
      - 3
      - 5
      - 9